services:
  - type: web
    name: portfolio-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 10000
